package envfiles

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type Instance struct {
	Name           string
	EnvFile        string
	FQDN           string
	KubeconfigPath string
	HostIP         string
}

func ParseFile(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		line = strings.TrimPrefix(line, "export ")
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}

		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		value = strings.Trim(value, `"'`)
		value = expandValue(value)
		values[key] = value
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return values, nil
}

func ParseFileOptional(path string) (map[string]string, error) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return map[string]string{}, nil
		}
		return nil, err
	}
	return ParseFile(path)
}

func LoadInstances(environmentDir string) ([]Instance, error) {
	matches, err := filepath.Glob(filepath.Join(environmentDir, "*.env"))
	if err != nil {
		return nil, fmt.Errorf("glob environment files: %w", err)
	}
	sort.Strings(matches)

	instances := make([]Instance, 0, len(matches))
	for _, match := range matches {
		values, err := ParseFile(match)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", match, err)
		}

		name := strings.TrimSuffix(filepath.Base(match), ".env")
		instances = append(instances, Instance{
			Name:           name,
			EnvFile:        match,
			FQDN:           values["FQDN"],
			KubeconfigPath: values["KUBECONFIG_PATH"],
			HostIP:         values["K3D_HOST_IP"],
		})
	}

	return instances, nil
}

func FindInstance(environmentDir, name string) (Instance, error) {
	for _, instance := range []string{filepath.Join(environmentDir, name+".env")} {
		values, err := ParseFile(instance)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return Instance{}, err
		}

		return Instance{
			Name:           name,
			EnvFile:        instance,
			FQDN:           values["FQDN"],
			KubeconfigPath: values["KUBECONFIG_PATH"],
			HostIP:         values["K3D_HOST_IP"],
		}, nil
	}

	return Instance{}, fmt.Errorf("ecosystem %q not found", name)
}

func expandValue(value string) string {
	home, _ := os.UserHomeDir()
	return os.Expand(value, func(key string) string {
		if key == "HOME" && home != "" {
			return home
		}
		return os.Getenv(key)
	})
}

func FormatInstanceEnv(name, fqdn, hostIP string, apiPort int, kubeconfigPath, corednsManifestPath string) string {
	return fmt.Sprintf(`# Generated by ces-k3d for ecosystem '%s'
K3D_CLUSTER_NAME="%s"
K3D_HOST_IP="%s"
K3D_API_PORT="%d"
K3D_HTTP_PORT="80"
K3D_HTTPS_PORT="443"
FQDN="%s"
KUBECONFIG_PATH="%s"
K3D_COREDNS_CUSTOM_MANIFEST_PATH="%s"
`, name, name, hostIP, apiPort, fqdn, kubeconfigPath, corednsManifestPath)
}

func FormatCoreDNSManifest(fqdn string) string {
	return fmt.Sprintf(`apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ces-fqdn.override: |
    rewrite name exact %s ces-loadbalancer.ecosystem.svc.cluster.local
`, fqdn)
}
