apiVersion: v1
kind: Pod
metadata:
  name: etcd-client
  labels:
    app: ces
    app.kubernetes.io/name: etcd-client
spec:
  containers:
    - name: etcd-client
      image: bitnami/etcd:3.5.2-debian-10-r0
      command:
        - sleep
        - infinity
      env:
        - name: ETCDCTL_API
          value: "2"
        - name: ETCDCTL_ENDPOINTS
          value: http://etcd.ecosystem.svc.cluster.local:4001
  automountServiceAccountToken: true