package app

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type instanceFile struct {
	Name           string
	EnvFile        string
	FQDN           string
	KubeconfigPath string
	HostIP         string
}

func parseEnvFile(path string) (map[string]string, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	values := map[string]string{}
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		line = strings.TrimPrefix(line, "export ")
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}

		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		value = strings.Trim(value, `"'`)
		value = expandEnvValue(value)
		values[key] = value
	}

	if err := scanner.Err(); err != nil {
		return nil, err
	}

	return values, nil
}

func loadInstanceFiles(environmentDir string) ([]instanceFile, error) {
	matches, err := filepath.Glob(filepath.Join(environmentDir, "*.env"))
	if err != nil {
		return nil, fmt.Errorf("glob environment files: %w", err)
	}
	sort.Strings(matches)

	instances := make([]instanceFile, 0, len(matches))
	for _, match := range matches {
		values, err := parseEnvFile(match)
		if err != nil {
			return nil, fmt.Errorf("parse %s: %w", match, err)
		}

		name := strings.TrimSuffix(filepath.Base(match), ".env")
		instances = append(instances, instanceFile{
			Name:           name,
			EnvFile:        match,
			FQDN:           values["FQDN"],
			KubeconfigPath: values["KUBECONFIG_PATH"],
			HostIP:         values["K3D_HOST_IP"],
		})
	}

	return instances, nil
}

func findInstanceFile(environmentDir, name string) (instanceFile, error) {
	instance := filepath.Join(environmentDir, name+".env")
	values, err := parseEnvFile(instance)
	if err != nil {
		if os.IsNotExist(err) {
			return instanceFile{}, fmt.Errorf("ecosystem %q not found", name)
		}
		return instanceFile{}, err
	}

	return instanceFile{
		Name:           name,
		EnvFile:        instance,
		FQDN:           values["FQDN"],
		KubeconfigPath: values["KUBECONFIG_PATH"],
		HostIP:         values["K3D_HOST_IP"],
	}, nil
}

func formatInstanceEnv(name, fqdn, hostIP string, apiPort int, kubeconfigPath, corednsManifestPath string) string {
	return fmt.Sprintf(`# Generated by k3d/ces-k3d for ecosystem '%s'
K3D_CLUSTER_NAME="%s"
K3D_HOST_IP="%s"
K3D_API_PORT="%d"
K3D_HTTP_PORT="80"
K3D_HTTPS_PORT="443"
FQDN="%s"
KUBECONFIG_PATH="%s"
K3D_COREDNS_CUSTOM_MANIFEST_PATH="%s"
`, name, name, hostIP, apiPort, fqdn, kubeconfigPath, corednsManifestPath)
}

func formatCoreDNSManifest(fqdn string) string {
	return fmt.Sprintf(`apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ces-fqdn.override: |
    rewrite name exact %s ces-loadbalancer.ecosystem.svc.cluster.local
`, fqdn)
}

func expandEnvValue(value string) string {
	home, _ := os.UserHomeDir()
	return os.Expand(value, func(key string) string {
		if key == "HOME" && home != "" {
			return home
		}
		return os.Getenv(key)
	})
}
