apiVersion: k8s.cloudogu.com/v1
kind: Blueprint
metadata:
  labels:
    app.kubernetes.io/name: blueprint
    app.kubernetes.io/instance: blueprint-sample
    app.kubernetes.io/part-of: k8s-blueprint-operator
    app.kubernetes.io/created-by: k8s-blueprint-operator
  name: blueprint-4
spec:
  blueprint: |
    {
    "blueprintApi":"v2",
    "dogus":[
      {
        "name":"hallowelt/bluespice",
        "version":"4.5.4-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Gi"
          }
        }
      },
      {
        "name":"hallowelt/bluespice-collabpadsbackend",
        "version":"4.5.4-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "2Mi"
          }
        }
      },
      {
        "name":"hallowelt/bluespice-opensearch",
        "version":"2.17.1-4",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "150Mi"
          }
        }
      },
      {
        "name":"hallowelt/bluespice-mathoid",
        "version":"4.5.4-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"hallowelt/bluespice-pdfrenderer",
        "version":"4.5.4-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"hallowelt/mongodb",
        "version":"8.0.3-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "500Mi"
          }
        }
      },    
      {
        "name":"hallowelt/drawio",
        "version":"24.7.17-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"itz-bund/baseline",
        "version":"1.6.0-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"itz-bund/easyredmine",
        "version":"13.11.5-7",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "3Mi"
          }
        }
      },
      {
        "name":"itz-bund/teamscale",
        "version":"2024.7.3-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "25Mi"
          }
        }
      },
      {
        "name":"official/cas",
        "version":"7.0.8-13",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/cockpit",
        "version":"2.3.0-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"official/gotenberg",
        "version":"8.15.3-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"premium/grafana",
        "version":"10.3.3-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "100Mi"
          }
        }
      },
      {
        "name":"official/jenkins",
        "version":"2.492.1-0",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "100Gi"
          }
        }
      },
      {
        "name":"official/ldap",
        "version":"2.6.8-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/mysql",
        "version":"8.4.4-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Gi"
          }
        }
      },
      {
        "name":"official/nexus",
        "version":"3.75.0-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "200Gi"
          }
        }
      },
      {
        "name":"k8s/nginx-ingress",
        "version":"1.12.1-1",
        "targetState":"present"
      },
      {
        "name":"k8s/nginx-static",
        "version":"1.26.3-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "50Mi"
          }
        }
      },
      {
        "name":"official/plantuml",
        "version":"2025.0-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"official/postfix",
        "version":"3.9.3-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Mi"
          }
        }
      },
      {
        "name":"official/postgresql",
        "version":"14.17-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "5Gi"
          }
        }
      },
      {
        "name":"official/redis",
        "version":"6.2.17-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/redmine",
        "version":"5.1.6-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "7Gi"
          }
        }
      },
      {
        "name":"official/registrator",
        "version":"0.12.0-2",
        "targetState":"absent"
      },
      {
        "name":"official/scm",
        "version":"3.7.4-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "8Gi"
          }
        }
      },
      {
        "name":"official/smeagol",
        "version":"1.7.6-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"official/sonar",
        "version":"25.1.0-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "1Gi"
          }
        }
      },
      {
        "name":"official/usermgt",
        "version":"1.20.0-2",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "50Mi"
          }
        }
      },
      {
        "name":"premium/admin",
        "version":"2.13.1-4",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"premium/backup",
        "version":"1.12.1-3",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      },
      {
        "name":"premium/portainer",
        "version":"2.27.1-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "3Gi"
          }
        }
      },
      {
        "name":"premium/whitelabeling",
        "version":"1.1.0-1",
        "targetState":"present",
        "platformConfig": {
          "resource": {
            "minVolumeSize": "10Mi"
          }
        }
      }
    ],
    "config": {
      "global": {
        "present": {
          "exampleKey": "exampleValue"
        }
      }
    },
    "components": [
      {
        "name":"k8s/k8s-dogu-operator",
        "version":"3.5.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-dogu-operator-crd",
        "version":"2.6.0",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-service-discovery",
        "targetState":"present",
        "version":"1.3.4"
      },
      {
        "name":"k8s/k8s-component-operator",
        "targetState":"present",
        "version":"1.8.0"
      },
      {
        "name":"k8s/k8s-component-operator-crd",
        "targetState":"present",
        "version":"1.8.0"
      },
      {
        "name":"k8s/k8s-blueprint-operator",
        "targetState":"present",
        "version":"2.4.0"
      },
      {
        "name":"k8s/k8s-blueprint-operator-crd",
        "targetState":"present",
        "version":"1.2.0"
      },
      {
        "name":"k8s/k8s-etcd",
        "targetState":"present",
        "version":"3.5.15-1"
      },
      {
        "name":"k8s/k8s-ces-control",
        "version":"1.3.1",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-minio",
        "version":"2024.11.7-2",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-loki",
        "version":"3.3.2-1",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-promtail",
        "version":"2.9.1-7",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-prometheus",
        "targetState":"present",
        "version":"57.1.1-8"
      },
      {
        "name":"k8s/k8s-cert-manager",
        "version":"1.13.1-4",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-cert-manager-crd",
        "version":"1.13.1-4",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-backup-operator",
        "version":"1.3.3",
        "targetState":"present"
      },
      {
        "name":"k8s/k8s-velero",
        "targetState":"present",
        "version":"5.0.2-9",
        "deployConfig":{
          "overwriteConfig":{
            "volumesnapshotclass": {
              "driver": "pd.csi.storage.gke.io",
              "parameters": {
                "type": ""
              }
            },
            "velero": {
              "credentials": {
                "useSecret": true,
                "existingSecret": "velero-backup-target"
              },
              "initContainers": [
                {
                  "name": "velero-plugin-for-gcp",
                  "image": "velero/velero-plugin-for-gcp:v1.11.1",
                  "volumeMounts": [
                    {
                      "mountPath": "/target",
                      "name": "plugins"
                    }
                  ]
                },
                {
                  "name": "velero-plugin-for-csi",
                  "image": "velero/velero-plugin-for-csi:v0.5.1",
                  "volumeMounts": [
                    {
                      "mountPath": "/target",
                      "name": "plugins"
                    }
                  ]
                }
              ],
              "configuration": {
                "backupStorageLocation": [
                  {
                    "name": "default",
                    "provider": "velero.io/gcp",
                    "bucket": "mn-migration-backup",
                    "config": {
                      "serviceAccount": "mn-migration-backup@ces-migration-test.iam.gserviceaccount.com",
                      "kmsKeyName": "projects/ces-migration-test/locations/europe-west3/keyRings/mn-migration-backup/cryptoKeys/mn-migration-backup-key"
                    }
                  }
                ],
                "volumeSnapshotLocation": [
                  {
                    "name": "default",
                    "provider": "velero.io/gcp",
                    "config": {
                      "snapshotLocation": "europe-west3"
                    }
                  }
                ]
              }
            }
          }
        }
      }
    ]}
  blueprintMask: |
    {"blueprintMaskApi":"v1"}
  ignoreDoguHealth: true
  ignoreComponentHealth: true
  allowDoguNamespaceSwitch: false
