apiVersion: k8s.cloudogu.com/v1
kind: Restore
metadata:
  labels:
    app.kubernetes.io/name: restore
    app.kubernetes.io/instance: restore-sample
    app.kubernetes.io/part-of: k8s-backup-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8s-backup-operator
  name: restore-sample
spec:
  provider: velero
  backupName: backup-sample
