@startuml
!define CLOUDOGUURL https://raw.githubusercontent.com/cloudogu/plantuml-cloudogu-sprites/master

!includeurl CLOUDOGUURL/common.puml
!includeurl CLOUDOGUURL/dogus/cloudogu.puml
!includeurl CLOUDOGUURL/dogus/scm.puml
!includeurl CLOUDOGUURL/dogus/redmine.puml
!includeurl CLOUDOGUURL/dogus/nginx.puml
!includeurl CLOUDOGUURL/dogus/postgresql.puml
!includeurl CLOUDOGUURL/tools/k8s.puml
!define SECONDARY_COLOR #55EE55

rectangle "Cluster" as cluster <<$k8s>> {
  rectangle k8sapi as "K8s API-Server" <<$k8s>> #white
  rectangle k8sres as "*"

  rectangle "Namespace" as namespace <<$k8s>> #white {
    rectangle mgrComps as "K8s-Komponenten" #white {

      rectangle servdiscpod as "k8s-service-discovery Pod" {
        rectangle servdisc as "k8s-service-discovery" <<$cloudogu>> #white
      }
      note as servdiscnote #ffffee
        erzeugt Warp-Menü und
        ingress-Regeln, verwaltetet
        den Wartungsmodus
      end note

      rectangle k8scesctlpod as "k8s-ces-control Pod" {
        rectangle k8scesctl as "k8s-ces-control" <<$cloudogu>> #white
      }
      note as k8scesctlnote #ffffee
        emuliert GRPC-Dienst
        anstelle von cesappd
      end note

      rectangle oppod as "k8s-dogu-operator Pod" {
        rectangle dogurator as "k8s-dogu-operator" <<$cloudogu>> #white
      }
      note as doguratornote #ffffee
        steuert Dogu-CRD
        und damit Dogu-
        Installationen usw.
      end note

      rectangle setuppod as "k8s-ces-setup Pod" {
        rectangle setup as "k8s-ces-setup" <<$cloudogu>> #white
      }
      note as setupnote #ffffee
        Installiert initial
        benötigte Komponenten
      end note

      rectangle configuration  <<$k8s>> #white {
        file configmaps
        file secrets
      }

      note as confignote #ffffee
        Enthält Dogu-Config & Global-Config
      end note

      rectangle otherpod as "weitere Komponenten" <<$cloudogu>> {
      }

      confignote .. configuration
      setupnote .. setup
      doguratornote .. dogurator
      k8scesctlnote .. k8scesctl
      servdiscnote .. servdisc
    }

    setup -l-> configuration
    dogurator -u-> configuration
    servdisc -d-> configuration
    k8scesctl -u-> configuration

    rectangle dogus #white {

      rectangle nginxIngressPod as "nginx-ingress Pod" {
        DOGU_NGINX(nginxingress, "nginx ingress") #white
        note right of nginxingress #ffffee
          Reverse Proxy,
          Ingress Controller und
          Warp-Menü-Injektor
        end note
      }
      rectangle nginxstaticPod as "nginx-static Pod" {
        DOGU_NGINX(nginxstatic, "nginx-static") #white
        note bottom of nginxstatic #ffffee
          liefert statische
          Web-Ressourcen aus
        end note
      }

      rectangle postgresqlPod as "postgresql Pod" {
        DOGU_POSTGRESQL(postgresql, "PostgreSQL") #white
      }

      rectangle redminePod as "redmine Pod" {
        DOGU_REDMINE(redmine, "Redmine") #white
      }

      rectangle scmPod as "scm Pod" {
         DOGU_SCM(scm, "SCM-Manager") #white
      }
    }
  }
}

actor user
actor admin
rectangle kubectlces as "kubectl-ces-plugin" <<$cloudogu>>

'styling
dogus -[hidden]u- mgrComps
scm -[hidden]d-> redmine
nginxingress -[hidden]d-> postgresql
redmine -[hidden]-> scm

admin --> k8sapi
k8sapi --> k8sres : managed alle \nRessourcen
admin -> kubectlces
kubectlces --> k8sapi

user --d-> nginxingress
nginxingress -r-> nginxstatic
nginxingress <-d-> scm
nginxingress <-d-> redmine
redmine <-d-> postgresql



legend bottom right
  Nicht im Bild:
  Notwendige Kubenetes-Ressourcen der abgebildeten
  Komponenten (z. B. Deployments, Services, usw.)
endlegend

caption Kubernetes-Cluster mit einer Dogu-Auswahl und wichtigen CES-Komponenten
@enduml